// <auto-generated />
using System;
using EFCorePractice;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCorePractice.Migrations
{
    [DbContext(typeof(ProjectContext))]
    [Migration("20260726065336_intialCreate")]
    partial class intialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFCorePractice.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DepartmentNumber")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ManageStartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("DepartmentId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("departments");
                });

            modelBuilder.Entity("EFCorePractice.Models.DepartmentLocation", b =>
                {
                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("DeptLocation")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("DepartmentId", "DeptLocation");

                    b.ToTable("departmentLocations");
                });

            modelBuilder.Entity("EFCorePractice.Models.Dependent", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("DependentName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DependentBirthDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DependentRelationship")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DependentSex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId", "DependentName");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("dependents");
                });

            modelBuilder.Entity("EFCorePractice.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeBDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeSex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("EmplyeeSalary")
                        .HasColumnType("float");

                    b.Property<string>("Ssn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SupervisorId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("SupervisorId");

                    b.ToTable("employees");
                });

            modelBuilder.Entity("EFCorePractice.Models.EmployeeProject", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectNumber")
                        .HasColumnType("int");

                    b.Property<int>("ProjectHours")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId", "ProjectNumber");

                    b.HasIndex("ProjectNumber");

                    b.ToTable("employeeProjects");
                });

            modelBuilder.Entity("EFCorePractice.Models.Project", b =>
                {
                    b.Property<int>("ProjectNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectNumber"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("ProjectLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjecutorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProjectNumber");

                    b.HasIndex("DepartmentId");

                    b.ToTable("projects");
                });

            modelBuilder.Entity("EFCorePractice.Models.Department", b =>
                {
                    b.HasOne("EFCorePractice.Models.Employee", "Emp")
                        .WithMany("dept")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Emp");
                });

            modelBuilder.Entity("EFCorePractice.Models.DepartmentLocation", b =>
                {
                    b.HasOne("EFCorePractice.Models.Department", "department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("department");
                });

            modelBuilder.Entity("EFCorePractice.Models.Dependent", b =>
                {
                    b.HasOne("EFCorePractice.Models.Employee", "Employee")
                        .WithOne("dependent")
                        .HasForeignKey("EFCorePractice.Models.Dependent", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EFCorePractice.Models.Employee", b =>
                {
                    b.HasOne("EFCorePractice.Models.Department", "department")
                        .WithMany("Employee")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFCorePractice.Models.Employee", "supervisor")
                        .WithMany("employees")
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("department");

                    b.Navigation("supervisor");
                });

            modelBuilder.Entity("EFCorePractice.Models.EmployeeProject", b =>
                {
                    b.HasOne("EFCorePractice.Models.Employee", "emp")
                        .WithMany("EmpProjects")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFCorePractice.Models.Project", "project")
                        .WithMany("EmpProjects")
                        .HasForeignKey("ProjectNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("emp");

                    b.Navigation("project");
                });

            modelBuilder.Entity("EFCorePractice.Models.Project", b =>
                {
                    b.HasOne("EFCorePractice.Models.Department", "Department")
                        .WithMany("Projects")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("EFCorePractice.Models.Department", b =>
                {
                    b.Navigation("Employee");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("EFCorePractice.Models.Employee", b =>
                {
                    b.Navigation("EmpProjects");

                    b.Navigation("dependent")
                        .IsRequired();

                    b.Navigation("dept");

                    b.Navigation("employees");
                });

            modelBuilder.Entity("EFCorePractice.Models.Project", b =>
                {
                    b.Navigation("EmpProjects");
                });
#pragma warning restore 612, 618
        }
    }
}
